-- ============================================================
-- Migration 009: Ficha do aluno de Novos Membros + reaproveitamento
-- (já aplicada via MCP em 2026-07-13)
-- ============================================================
-- student_forms: ficha completa preenchida pelo próprio aluno (ou
-- por um voluntário para quem não sabe/não tem celular/é idoso).
-- Aceite do estatuto substitui o antigo termo LGPD.
-- Bucket 'student-photos' criado no storage para as fotos.
--
-- new_members_enrollments.credited_lessons + credit_note:
-- reaproveitamento de aulas quando o aluno rematricula sem ter
-- concluído a turma anterior.
-- (SQL completo aplicado — ver Supabase)

-- ============================================================
-- Migrations posteriores (aplicadas via MCP, resumo):
-- 010: student_forms.spouse_name, marriage_date (cônjuge quando casado)
-- 011: new_members_lessons.title2 (2 matérias por encontro)
--      churches.nm_default_lessons (modelo de aulas pré-definido)
--      scheduled_messages: person_id nullable, custom_message, lesson_id
--        (lembrete direto do professor 1 dia antes da aula)
-- ============================================================
-- 012: nm_teachers (professor só nome+WhatsApp, FK repointada)
-- 013: gca_requests (solicitações de inclusão/transferência) +
--      policy UPDATE em discipleship_observations (corrige edição)
-- 014: surveys, survey_targets, survey_responses (pesquisas dos GCAs)
-- 015: FKs para profiles em ON DELETE SET NULL (permite excluir usuário
--      preservando o histórico) + profiles.id CASCADE de auth.users
